### ISSUE TITLE
Support use with Docker

### ISSUE THREAD

**Issue by eemcmullan** [konveyor/kantra#164]
Right now, kantra defaults to podman to run commands in containers. An env var `PODMAN_BIN` can be used to override it with docker. We want to allow kantra to detect docker use, if available, without the user having to define this variable.

**Comment by ascheman** [comment]
Wouldn't it be sufficient to replace the one and only (currently) [call to the `podman` (`docker`) binary](https://github.com/konveyor/kantra/blob/7ed233deb45b0beedc0d6cfbf1e017b0c061dbb5/cmd/container.go#L185) by a suitable use of a respective library, e.g., https://pkg.go.dev/github.com/docker/docker/client?

Then only the installation guide (README.md) would be left with a hard coded use of `podman` to set up Kantra.

**Comment by shawn-hurley** [comment]
IIUC, and please correct me if I am incorrect; the docker engine client uses the API to call into a docker to take action.

While this is also supported in Podman, I can't see this as a shared, agreed-on spec in OCI. While I doubt this would change, it is just something I am a little worried about. Specifically, I am looking at this part of the [https://github.com/opencontainers/runtime-spec/blob/main/glossary.md#runtime-caller]

> Runtime callers often execute a runtime via [runc](https://github.com/opencontainers/runc)-compatible command line interface; however, its interaction interface is currently out of the scope of the Open Container Initiative Runtime Specification.

It sounds like there are no defined specs for external callers, but I feel like I would be more comfortable using the CLI interface because of the line around `runc.` 

Like I said I could be incorrect, and if there is some other place to look please point me to it, I honestly have no idea, just thoughts on what I am reading. 

There is also the concern about having a dependency on Moby, as, in the past, this has caused me lots of pain. It may not be a real concern anymore just some past experience that I want to add to the conversation.

**Comment by eemcmullan** [comment]
Resolved in https://github.com/konveyor/kantra/pull/165

**Comment by ascheman** [comment]
If I look into the code of #165, I wonder how I could enforce using `docker` via `${PODMAN_BIN}` if there is a `podman` on the path?

**Comment by shawn-hurley** [comment]
https://github.com/konveyor/kantra/pull/165/files#diff-33b6837c599c9f67320ec38678d366528089e4a5db0f786203c3af5c9898bd66R45-R47

If PODMAN_BIN is set, it will use that AFAICT

**Comment by ascheman** [comment]
Of course, your right as the `Load()` function only makes sure the path is known/set to the Config struct ...
