### ISSUE TITLE
[BUG] disable provider option is not available

### ISSUE THREAD

**Issue by midays** [konveyor/kantra#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

v0.5.0-beta.3

### Priority

Major

### Current Behavior

Runing the kantra command with the disable-provider option fails

kantra analyze --input /home/midays/Documents/projects/maven-typescript-example --target cloud-readiness --disable-provider java-external-provider
Error: unknown flag: --disable-provider

### Expected Behavior

The option should be recognized

### How Reproducible

Always (Default)

### Steps To Reproduce

Run the command:
`$ kantra analyze --input /home/midays/Documents/projects/maven-typescript-example --target cloud-readiness --disable-provider java-external-provider `

### Environment

```markdown
- OS:
```

**Comment by eemcmullan** [comment]
My apologies here, I probably forgot to update this somewhere. Instead of `--disable-provider` we have `--provider` which forces one or more providers to run. For example: `--provider java` will run ONLY the Java provider,.`--provider java --provider dotnet` will run both the Java and .Net providers.

**Comment by eemcmullan** [comment]
Closing with above resolution
